### ISSUE TITLE
.py

### ISSUE THREAD

**Issue by romaissaghdjt** [edityomurti/ReportManagementClient#1]
Hi thank u for ur app ^^
 I have an application for  diagnostic medical but I need help on python 
if u  can help me please

**Comment by edityomurti** [comment]
Hi @romaissaghdjt , 
Does your application related to this project?

if yes, Can you elaborate your application and the relation with this project?
if not, I will close this issue and you can reach me by email at edit@extrainteger.com .

thanks

**Comment by romaissaghdjt** [comment]
it s okey ... Sorry for the delay ^^

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫في الاثنين، 31 ديسمبر 2018 في 12:48 م تمت كتابة ما يلي بواسطة ‪Swakresna
Edityomurti‬‏ <‪notifications@github.com‬‏>:‬
